<a href="https://colab.research.google.com/github/Harshitt-10/Colab/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np

# **Create**

In [3]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2),7)
ones = np.ones((2,2,2))

In [4]:
data

array([[[0.79234214, 0.56547962, 0.43442836, 0.16609289],
        [0.24267138, 0.90601575, 0.69427242, 0.07424053],
        [0.25298004, 0.18236096, 0.02215848, 0.09200437]],

       [[0.44650235, 0.31028214, 0.90507011, 0.87780979],
        [0.50398618, 0.7475146 , 0.55557738, 0.00242337],
        [0.67571838, 0.87263699, 0.96626689, 0.98211075]]])

In [5]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [6]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [7]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
type(arr)

numpy.ndarray

## **Read**

In [11]:
#Attributes
shape = arr.shape
size = arr.size
types = arr.dtype

In [12]:
shape

(2, 4)

In [13]:
size

8

In [14]:
types

dtype('int64')

In [21]:
#Slicing
arr1 = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [16]:
data

array([[[0.79234214, 0.56547962, 0.43442836, 0.16609289],
        [0.24267138, 0.90601575, 0.69427242, 0.07424053],
        [0.25298004, 0.18236096, 0.02215848, 0.09200437]],

       [[0.44650235, 0.31028214, 0.90507011, 0.87780979],
        [0.50398618, 0.7475146 , 0.55557738, 0.00242337],
        [0.67571838, 0.87263699, 0.96626689, 0.98211075]]])

In [17]:
arr1

array([[0.79234214, 0.56547962, 0.43442836, 0.16609289],
       [0.24267138, 0.90601575, 0.69427242, 0.07424053],
       [0.25298004, 0.18236096, 0.02215848, 0.09200437]])

In [22]:
slicer

array([[0.79234214, 0.56547962, 0.43442836, 0.16609289],
       [0.24267138, 0.90601575, 0.69427242, 0.07424053]])

In [19]:
reverse

array([[0.44650235, 0.31028214, 0.90507011, 0.87780979],
       [0.50398618, 0.7475146 , 0.55557738, 0.00242337],
       [0.67571838, 0.87263699, 0.96626689, 0.98211075]])

In [20]:
singleval

np.float64(0.7923421360688121)

# **Update**

In [23]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [24]:
list1

array([0.67300028, 0.0218367 , 0.85280823, 0.31465148, 0.70981348,
       0.11974607, 0.55244156, 0.37720208, 0.79183977, 0.7897843 ])

In [25]:
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
mul = np.multiply(list1, list2)
div = np.divide(list1, list2)
dot = np.dot(list1, list2)

In [26]:
add

array([1.23390197, 0.21698239, 1.2801634 , 1.30166284, 0.99854764,
       0.17465694, 0.97822086, 0.3782301 , 1.28753736, 1.35217539])

In [27]:
sub

array([ 0.1120986 , -0.17330899,  0.42545306, -0.67235988,  0.42107932,
        0.0648352 ,  0.12666226,  0.37617405,  0.29614218,  0.22739321])

In [28]:
mul

array([3.77486995e-01, 4.26133753e-03, 3.64452005e-01, 3.10564584e-01,
       2.04947398e-01, 6.57536091e-03, 2.35218180e-01, 3.87774120e-04,
       3.92513069e-01, 4.44167656e-01])

In [29]:
div

array([1.19985427e+00, 1.11899464e-01, 1.99554911e+00, 3.18792156e-01,
       2.45836339e+00, 2.18073523e+00, 1.29748336e+00, 3.66918264e+02,
       1.59742508e+00, 1.40433288e+00])

In [30]:
dot

np.float64(2.340574359395669)

In [32]:
#SAPLEMM
sqrt = np.sqrt(25)
ab = np.abs(-3)
power = np.power(2, 10)
log = np.log(64)
exp = np.exp([2, 3])
mins = np.min(list1)
maxs = np.max(list2)

In [33]:
sqrt

np.float64(5.0)

In [34]:
ab

np.int64(3)

In [35]:
power

np.int64(1024)

In [36]:
log

np.float64(4.1588830833596715)

In [37]:
exp

array([ 7.3890561 , 20.08553692])

In [38]:
mins

np.float64(0.021836698159739654)

In [39]:
maxs

np.float64(0.9870113589878661)

In [40]:
data

array([[[0.79234214, 0.56547962, 0.43442836, 0.16609289],
        [0.24267138, 0.90601575, 0.69427242, 0.07424053],
        [0.25298004, 0.18236096, 0.02215848, 0.09200437]],

       [[0.44650235, 0.31028214, 0.90507011, 0.87780979],
        [0.50398618, 0.7475146 , 0.55557738, 0.00242337],
        [0.67571838, 0.87263699, 0.96626689, 0.98211075]]])

In [41]:
data[0][0][0] = 500

In [42]:
data

array([[[5.00000000e+02, 5.65479618e-01, 4.34428355e-01, 1.66092890e-01],
        [2.42671377e-01, 9.06015754e-01, 6.94272420e-01, 7.42405285e-02],
        [2.52980045e-01, 1.82360959e-01, 2.21584752e-02, 9.20043678e-02]],

       [[4.46502354e-01, 3.10282135e-01, 9.05070108e-01, 8.77809792e-01],
        [5.03986180e-01, 7.47514599e-01, 5.55577379e-01, 2.42337241e-03],
        [6.75718384e-01, 8.72636995e-01, 9.66266886e-01, 9.82110752e-01]]])

In [43]:
data.sort()
data

array([[[1.66092890e-01, 4.34428355e-01, 5.65479618e-01, 5.00000000e+02],
        [7.42405285e-02, 2.42671377e-01, 6.94272420e-01, 9.06015754e-01],
        [2.21584752e-02, 9.20043678e-02, 1.82360959e-01, 2.52980045e-01]],

       [[3.10282135e-01, 4.46502354e-01, 8.77809792e-01, 9.05070108e-01],
        [2.42337241e-03, 5.03986180e-01, 5.55577379e-01, 7.47514599e-01],
        [6.75718384e-01, 8.72636995e-01, 9.66266886e-01, 9.82110752e-01]]])

In [44]:
print(data.shape)

(2, 3, 4)


In [45]:
data = data.reshape((2,2,-1))  #-1 means we dont care about the size of last dimension and it automatically calculates it.
data.shape

(2, 2, 6)

In [46]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [47]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# **Delete**

In [48]:
data

array([[[1.66092890e-01, 4.34428355e-01, 5.65479618e-01, 5.00000000e+02,
         7.42405285e-02, 2.42671377e-01],
        [6.94272420e-01, 9.06015754e-01, 2.21584752e-02, 9.20043678e-02,
         1.82360959e-01, 2.52980045e-01]],

       [[3.10282135e-01, 4.46502354e-01, 8.77809792e-01, 9.05070108e-01,
         2.42337241e-03, 5.03986180e-01],
        [5.55577379e-01, 7.47514599e-01, 6.75718384e-01, 8.72636995e-01,
         9.66266886e-01, 9.82110752e-01]]])

In [49]:
np.delete(data, 0, axis=1)

array([[[0.69427242, 0.90601575, 0.02215848, 0.09200437, 0.18236096,
         0.25298004]],

       [[0.55557738, 0.7475146 , 0.67571838, 0.87263699, 0.96626689,
         0.98211075]]])

In [50]:
np.save("new array", data)

In [51]:
test = np.load("new array.npy")
test

array([[[1.66092890e-01, 4.34428355e-01, 5.65479618e-01, 5.00000000e+02,
         7.42405285e-02, 2.42671377e-01],
        [6.94272420e-01, 9.06015754e-01, 2.21584752e-02, 9.20043678e-02,
         1.82360959e-01, 2.52980045e-01]],

       [[3.10282135e-01, 4.46502354e-01, 8.77809792e-01, 9.05070108e-01,
         2.42337241e-03, 5.03986180e-01],
        [5.55577379e-01, 7.47514599e-01, 6.75718384e-01, 8.72636995e-01,
         9.66266886e-01, 9.82110752e-01]]])